### ISSUE TITLE
This slick-joda-mapper doesn't seem to take into account timezone when converting to sql.Timestamp

### ISSUE THREAD

**Issue by dk8996** [tototoshi/slick-joda-mapper#29]
See this for more info:
http://stackoverflow.com/questions/14070572/is-java-sql-timestamp-timezone-specific

I think some of the code should be like this:
` p.setTimestamp(idx, toSqlType(v),Calendar.getInstance(v.getZone))`

**Comment by tototoshi** [comment]
Fixed by #30
