### ISSUE TITLE
Unable to find 2.0.0.0-SNAPSHOT version

### ISSUE THREAD

**Issue by Xeloss86** [tototoshi/slick-joda-mapper#31]
Hi team,

First of all, thanks a lot for developing such a useful framework. 

I just tried to add "  "com.github.tototoshi" %% "slick-joda-mapper" % "2.0.0-SNAPSHOT""  to my build.sbt file, but it is thoriwng "unresolved Dependency" error.

sbt.ResolvedException: unresolved dependency: com.github.totoshi#slick-jodamapper_2.11;2.0.0-SNAPSHOT:  not found.

![build sbt screenshot](https://cloud.githubusercontent.com/assets/795143/6993654/02b91986-db2e-11e4-9a59-f1763d10d241.png)
![joda_mapper_error](https://cloud.githubusercontent.com/assets/795143/6993655/08b78e94-db2e-11e4-9633-8277f891e2a9.png)

Please help! 

Many Thanks,

Joo

**Comment by tototoshi** [comment]
Please add this line to build.sbt

```scala
resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```
