### ISSUE TITLE
GenericJodaSupport should be trait

### ISSUE THREAD

**Issue by margussipria** [tototoshi/slick-joda-mapper#36]
Using something like:

```scala
trait GenericJodaSupport { driver: JdbcDriver =>
  // code
}

object PostgresJodaSupport extends PostgresDriver with GenericJodaSupport
```

instead of current 
```scala
class GenericJodaSupport(val driver: JdbcDriver) {
  // code
}

object PostgresJodaSupport extends GenericJodaSupport(PostgresDriver)
```

would be better if somebody would like to use GenericJodaSupport as mixin with `slick.driver.API`.

That way you don't need import *Support object every time separately.

**Comment by tototoshi** [comment]
I don't want to change the interface for the reason of compatibility.

**Comment by gmalouf** [comment]
Couldn't we expose an interface without breaking compatibility?  In my use case, I have a base trait for timestamped columns (created_at/updated_at).  In my ideal scenario, I would mix GenericJodaSupport into my TimestampedColumns trait, then have all my tables extend this single trait.  

Today, I have to import JodaSupport into both my timestamp trait and all of the tables that extend it - pretty ugly side-effect.
