### ISSUE TITLE
Build for Slick 3.2.0 / Scala 2.12

### ISSUE THREAD

**Issue by mslinn** [tototoshi/slick-joda-mapper#47]
[Slick 3.2.0-RC1 / Scala 2.12](http://slick.lightbend.com/news/2017/02/10/slick-3.2.0-RC1-released.html) is available.

**Comment by mslinn** [comment]
Slick 3.2.0 final was just released http://slick.lightbend.com/news/2017/02/24/slick-3.2.0-released.html

**Comment by yurique** [comment]
#49 added support for this and is merged in.

**Comment by hhandoko** [comment]
Hi fellas, any ETA for Maven Central release?

**Comment by yurique** [comment]
@hhandoko looks like it's out (2.3.0 for 2.12):  
http://repo1.maven.org/maven2/com/github/tototoshi/slick-joda-mapper_2.12/2.3.0/

**Comment by hhandoko** [comment]
@yurique thanks, unfortunately I'm still stuck with 2.11 until next version of Play comes out. Will there be support for 2.11?
