### ISSUE TITLE
slick-joda-mapper  : 2.3.0 with    scala 2.11 is not available on maven central

### ISSUE THREAD

**Issue by dgouyette** [tototoshi/slick-joda-mapper#50]
The latest version is not available on maven central : 

https://mvnrepository.com/artifact/com.github.tototoshi/slick-joda-mapper_2.11

**Comment by francisdb** [comment]
Can we expect anything soon?

**Comment by francisdb** [comment]
Some more info on why we need this:
play-slick 2.1.0 for play 2.5.x uses slick 3.2.0 on scala 2.11.x
play 2.6.x for scala 2.12 is not available yet

**Comment by mslinn** [comment]
+1, another vote for this version

**Comment by lars-n** [comment]
also +1, running on slick 3.2 and scala upgrade to 2.12 is not possible.

**Comment by AnyRoad** [comment]
+1, it would be nice to have version 2.3.0 with Scala 2.11.

**Comment by lars-n** [comment]
@tototoshi any news on when this can be published? Cheers

**Comment by tototoshi** [comment]
published now.
sorry for the late reply.
